### ISSUE TITLE
Finish expenditures report in management reports

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/libsys-webforms#183]
`expend_rpt.request_circ_2_insert` inserts valid params into `EXPENDITURES_CIRC_LOG` table. Anything else the rails app needs to do?

Related to #110

**Comment by matthewahmed** [comment]
Some issues with selecting fund(s) and date range affect other reports as well.

The list for selecting funds looks OK for individual funds, but when "Fund ID begins with" is selected, the drop down list is not populated (from EXPENDITURES_FUNDS).

The resulting entry in the TA_FUND_CODE column (different column name other reports) should not have the quotes, brackets and space
["1065031-119-AABNK"] should be 1065031-119-AABNK
["1065031-105-KBADW", "1026056-1-AABNN"] should be
1065031-105-KBADW,1026056-1-AABNN

The DATE_RANGE_START and DATE_RANGE_END columns get valid values when a Calendar Year date range is entered, but they make no sense for Fiscal Year or Pay Date ranges. Maybe enter the same values using the current PL/SQL form and compare the table values to the new form's.

Some less vital issues:

The "End of Date Range" dropdown should default to "Same whatever as Start", like the PL/SQL forms. Users most often request a single fiscal year, so that default is usually correct.

The Date Range dropdown lists should have the latest years at the top (Pay Date is already sorted that way).

The radio buttons for date range type don't show they're selected.

**Comment by tallenaz** [comment]
Commit [285a838](https://github.com/sul-dlss/libsys-webforms/pull/198/commits/285a83849215b8f6e0ea8afccdfd778bb1557be2) gets the drop down list populated when 'Fund ID begins with' is selected.

**Comment by tallenaz** [comment]
Commit [b9fd728](https://github.com/sul-dlss/libsys-webforms/pull/199/commits/b9fd728a04a572a51ea6df1104104723cfa686a7) saves the fund(s) selected for TA_FUND_CODE as a comma-separated string.

**Comment by tallenaz** [comment]
Commit [05e74ce](https://github.com/sul-dlss/libsys-webforms/pull/200/commits/05e74ce4f0a8357b0397ff41ec695cf009324674) changes the pay_date range formatting to make sense for DATE_RANGE_START and _END

**Comment by tallenaz** [comment]
Commit [db7d7d2](https://github.com/sul-dlss/libsys-webforms/pull/201/commits/db7d7d2ae2902ca7825a4f01904c3476b52b0647) makes sense of fiscal year ranges by selecting them from EXPENDITURES_FY_DATES

**Comment by tallenaz** [comment]
The rails app lets the user save an expenditure report without selecting any kind of year, leaving the DATE_RANGE_START and _END fields empty. The PL/SQL app makes fiscal year the default type that will get selected unless the user selects another kind of year. This approach could work in the rails app, but since the rails app fires off some javscript to reveal the date selectors once the user selects a type of year, making fiscal year the default leaves the date selectors hidden. In any case, I'll work on getting the rails app to require that the user has selected a type of year.

**Comment by tallenaz** [comment]
Commit [740eb13](https://github.com/sul-dlss/libsys-webforms/pull/202/commits/740eb13bc8561ca67530362ce18dc05f1292391c) sets a validation on the `date_type` radio buttons, so that the user has to pick a type of year to create a report.

**Comment by tallenaz** [comment]
Now that the user has to pick a kind of year, the rails app still lets the user save a report if no particular start or end year is selected. But we want to have the end date range default to whatever the start date is, so the start date should be something.

**Comment by tallenaz** [comment]
Commit [22d411b](https://github.com/sul-dlss/libsys-webforms/pull/206/commits/22d411b181bc397aed86f9958fd50bf4dcd98b23) sets defaults and expands callbacks for fiscal, calendar and pay date years so that users can select a single year's range more conveniently.
