### ISSUE TITLE
Strip empty array object at start of array in management reports for libraries

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/libsys-webforms#278]
Is this is a problem for the running of the report? In the circulation_statistics_report, and the expenditures_with_circ_stats, rails adds an empty
Libraries: `["", "ART", "BIOLOGY", "CLASSICS"]`

This should be done in the models `CirculationStatisticsReportLog` and `ExpendituresWithCircStatsReport`

**Comment by matthewahmed** [comment]
These arrays have to be converted to table column entries, presumably discarding the empty member in that process, LIBS_LOCS column in CIRC_STATS_RPT_LOG table or LIBRARIES in EXPENDITURES_CIRC_LOG.

EXPENDITURES_CIRC_LOG is simpler because no locations filter. LIBRARIES column is null for "All Libraries", otherwise a comma separated list of libraries. An extra comma (e.g. **ART,** or **,ART,SAL**) would cause an error. Spaces or quotes would also cause an error. If formatting the table entry this way is impractical, I can update the PL/SQL to handle it.

CIRC_STATS_RPT_LOG can have just a comma separated list of libraries like above in LIBS_LOCS, if the user chose "All Formats" for every library. Any library with a location filter is followed by a slash separated list of its selected locations, e.g.:
ART/MEDIA/STACKS,GREEN/STACKS,LAW,SAL3/STACKS
In the above, LAW is "All Formats"

**Comment by tallenaz** [comment]
If I remember correctly, there's some javascript that converts the rails array into the table column entries -- I don't think the empty first element is a problem for the running of the report.

**Comment by jgreben** [comment]
👍
