### ISSUE TITLE
Consider new page for User Access Management

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#374]
New column in authorized_user table for user_access_mgt (or whatever for column name).

Page would allow a user to add/remove another Name/SUNetID for various other columns.

Would get LibSys out of the business of having to grant access to new users!

**Comment by matthewahmed** [comment]
Instead of a new column, how about making some users "Administrators" of particular column(s) they currently have a 'Y' in? That way those Administrators can add permission only for specific app(s), instead of power over every app column in AUTHORIZED_USER.

Currently users have 'Y' for whatever app columns they have permission for, NULL (or no user row) if they don't have permission. I suggest adding a new value 'A' (Administrator) for users who are allowed to add or remove users from that column (plus same app permissions as 'Y' users).

The "Add/remove user" web page would show all columns that the user has an 'A' entry in, with controls to add or remove users.

**Comment by shelleydoljack** [comment]
Fixed by #418
