### ISSUE TITLE
Imprint data should pull from 260 AND 264 for management reports

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#430]
Placeholder... I believe it is the PL/SQL code that would need to be updated in order to get the right imprint.

Imprint is in 260, but for RDA is in 264, which is repeatable.  Should only have 260 OR 264(s).

Not sure if imprint data is already in expenditures table when expenditure report is run, or if expenditure report itself does a sel for imprint/bib data.

**Comment by dlrueda** [comment]
Follow up meeting with Acquisitions folks... since this data is being asked for on Expenditure reports, that is for mostly current records, and they feel that most records would have imprint info in the 264 instead of the 260.  Maybe we could switch to using the 264 instead of 260.

But, is the code used for circ reports as well, or just expenditures. I think this is in PL/SQL code, not libsys-webforms.

**Comment by rlunnon** [comment]
The expenditures table includes a column CA_PUB260 which takes the imprint data from the 260 tag only. 
Many newly loaded bib records still use the 260, so it is not feasible to switch to 264. 

In the case of multiple 264 tags, the first one should be output.
 
Reports to include 260/264:
LIB Expenditures report
LIB Expenditures with Circ stats report
LIB Open Orders report (Encumbrances)

**Comment by shelleydoljack** [comment]
It looks like the column CA_PUB260 is getting populated by the PL/SQL function expend_rpt.selcatalog_to_table, which is calling `selcatalog -oTAe -e"008,260"` somewhere. We will need to add 264 to that selcatalog call, which I think will only grab the first one (which it does with other tags that repeat) and then have some function that grabs the data from the 264 if the 260 is empty.

**Comment by shelleydoljack** [comment]
In expend_rpt package is a function run_sel_cmds_queries. I think this is the selcatalog getting called:
```
/************************************************************
    selcatalog
  ************************************************************/
  if not file_create_wrapper(gfn_selcatalog_out, v_ret) or
     not file_create_wrapper(gfn_selcatalog_err, v_ret)
  then
    return v_ret;
  end if;

  -- Each line of selcatalog_in is:
  -- catalog key | call sequence | selector      -- selorderlin -oN"W.9008."
  -- inv_line_key | fund_code |                  -- From table
--  if host('cat ' || gfp_selcatalog_in || ' | selcatalog -iC '
  if host('cat ' || gfp_selcatalog_in || ' | selcat_depipe.pl -iC ' ||
--          ' -oTAeS -e"008,260"  2> ' ||
-- Kitchen sink: Add 8 fields: 020,022,024,962,440,490,830,format
-- Need matching update in selcatalog_to_table
-- Maybe also add 800,810,811, but they're unwieldy, author oriented
          ' -oTAefvSC -e"008,260,020,022,024,962,440,490,830"  2> ' ||
          gfp_selcatalog_err || ' > ' || gfp_selcatalog_out)
     is null
  then
    return 'null return for selcatalog host call';
  end if;

  if not to_log('selcatalog lines returned:  ' ||
--                host_output('wc -l < ' || gfp_selcatalog_out), v_ret)
                -- wc -l doesn't handle Unicode correctly
                host_output('grep -c "" < ' || gfp_selcatalog_out), v_ret)
  then
    return v_ret;
  end if;

  -- Each line in selcatalog_out is:
  -- title | author | 008 fld | 260 fld |      -- selcatalog -oTAe -e"008,260"
  -- 020 fld | 022 | 024 | 962 | 440 | 490 | 830 |  -- more -e for kitchen sink
  -- format | year |                            --   -ofv for kitchen sink
  -- call sequence | selector |                -- selorderlin -oN"W.9008."
  -- inv_line_key | fund_code |                -- From table
  -- ordlin copies | ordlin create date|  -- selorderlin -okc (Added Delphi)
  -- ckey|    -- selcatalog -o...C    Not used except for diagnostic
```

**Comment by shelleydoljack** [comment]
I updated expend_rpt package on LTRXDEV2 to take the 264 as well and ran some tests. It seems to work fine. This is how I ran the tests:

1. Run delphi_pay.debug_run on LTRXDEV2 (I killed the process sometime in the middle b/c I kicked it off from the command line and it was running long and I had to go).
2. Look at the log file to see if there are any invoices selected:
```
sirsi@symphony-app-dev-1 /s/SUL/SUL_oracle> cat delphi2002141145_log_test
14-FEB-2020 11:45:22  Begin DELPHI_PAY.do_payments(14-FEB-2020)
p_lockdate_cutoff = "include today"
v_lockdate_cutoff = "includetoday"
11:45:27  Begin payment_steps
11:46:55  296994 rows of TEST/REJECTED runs moved to delphi_payments_recover
11:47:01  check_del_pay_table_ready finished
11:47:45  14097 invoices selected for
          date locked after 20180222 and before 20200215
11:47:55  get_invoice_list_new finished
11:58:02  run_sel_cmds finished
11:58:25  217678 invline/fund lines read
          99475 TAXADJUST lines found
11:58:35  sel_tax_invlines_to_table finished
```
3. Run query on LTRXPRD1 on an invoice ID that error'd on LTRXDEV2, such as:
```
SELECT row_create_date, row_mod_date, row_type, status, pay_date, invoice_date, lib, invoice_id, invoice_key,
   inv_line_no, invline_key, invline_type, invline_price, funding_amt, funding_type, funding_pct, pay_out, tax_type,
   ordline_key, fund_key, fund_id, expend_type, terms, attach, inv_sort, del_vend, del_site, vnd_name, vnd_id,
   shdw_ord_id, note, uni_date_paid, delphi_date, session_note, run_type, order_id, ord_line_num, fiscal_yr, currency
FROM delphi_payments
where pay_date < sysdate - 1
and pay_date > sysdate - 800
and invoice_id = '309750'
order by pay_date desc, invoice_id, inv_sort;
```
4.  Notice the values in columns note, delphi_date, session_note, run_type between the two databases. Update these values in LTRXDEV2 to match what's in LTRXPRD1 and schedule run of expenditures weekly processing in order to update the expenditures table (make sure to update run_type to DEFAULT or else the expend_rpt.weekly_processing won't pick it up and put in expenditures table):
```
begin
dbms_scheduler.create_job( job_name => 'EXPEND_RPT_WEEKLY_PROCESS_ONCE',
 job_action => 'expend_rpt.weekly_processing',
 job_type => 'STORED_PROCEDURE',
 enabled => true,
 auto_drop => true,
 start_date => sysdate );
end;
```
5. The log files get removed so quickly `ls -ltr /s/SUL/SUL_oracle` to get the log file (I don't recall if this log file gets saved somewhere; it doesn't get emailed):
```
sirsi@symphony-app-dev-1 /s/SUL/SUL_oracle> cat exp_load200214161717_log
load_table started FRI 14-FEB-20 16:17:17
DELPHI_PAYMENTS rows already done for pay_date <= 23-FEB-18
16:17:17  open_cursor done
16:17:17  First fetch done
16:17:19  11 delphi_payments row_type DR rows read
16:17:34  11 delphi_payments DR rows read
          11 expenditures rows written
          0 expenditures_error rows written
16:17:34  selorderlin lines returned: 11
          
16:17:49  0 lines written to selserctl_in
          11 lines written to selcatalog_in
```
6. Check the expenditures table for the data in CA_PUB260 (it should not be null for the recent run to update the table).
7. Check the records to see if they had a 264 in them, ckey is in expenditures.OL_CAT_KEY. Verify this data against what was written to the expenditures.CA_PUB260 column:
```
echo '12219346
> 12219347
> 12219348
> 12219349
> 12219350
> 8533921
> 12219352
> 12219353
> 12219354
> 12219355
> 12219351' | trs catalogdump -oF | grep "^\.26[04]\." -P
.264.  1|aBerlin ;|aBoston :|bDe Gruyter Mouton,|c[2017]
.264.  1|aBerlin :|bLit ;|aEast Lansing :|bMichigan State University Press,|c[2017]
.264.  1|a[Göttingen] :|bUniversitätsverlag Göttingen,|c2017.
.264.  1|aFrankfurt am Main :|bVervuert Verlag ;|aMadrid :|bIberoamericana,|c2017.
.264.  1|aMünster :|bAschendorff Verlag,|c[2017]
.264.  1|aTübingen :|bMohr Siebeck,|c[2017]
.264.  1|aTübingen :|bMohr Siebeck,|c[2017]
.264.  1|aStuttgart :|bIbidem-Verlag,|c[2017]
.264.  1|aWiesbaden :|bHarrassowitz Verlag, in Kommission,|c2017.
.264.  1|aTübingen :|bMohr Siebeck,|c[2017]
```
In the test run outlined above, everything checked out okay. ckey 8533921 got null in CA_PUB260 but that's b/c it is a `SHIP, MISC, or SERV fees (FY2010).` record with no 260/264 field.

- [x] Further testing needed?
- [x] Move expend_rpt body to LTRXPRD1

**Comment by dlrueda** [comment]
Shelley thanks for the awesome documentation of your process.

My only (super slight) hesitation is that all your expenditures lines pulled from the 264, and I would want to verify that it will still pull from the 260 if that's where the publication data is.

Re-read all the above and I'm not sure how you determined in step 3 which invoices error'd on LTRXDEV2?

I feel like perhaps  it's an abundance of caution to do another test on another invoice, making sure at least one of the bib records has a 260.  If you feel like that's overkill, then move to prod.  If it's not too much trouble to do the test with a mix of 260/264s, then one more test would be optimal.

**Comment by shelleydoljack** [comment]
I agree more tests would be good. As for step 3 from above, by “error’d” I meant that when running Delphi payments in debug mode on test, they all get that Test/rejected status and the expenditures table doesn’t update. Running Delphi payments in debug mode identifies invoice id’s to look up in the production database and futz the data on test so that I can get the expenditures table to update.

**Comment by shelleydoljack** [comment]
Ok, I ran another test. Here are the steps I completed:
1. Pick an invoice_key with RUN_TYPE = "TEST" from LTRXDEV2 from the recent debug run of delphi payments and query LTRXPRD1:
```
SELECT *
FROM delphi_payments
where  invoice_id = '309619'
order by pay_date desc, invoice_id, inv_sort;
```
2. Grab the catkeys from the expenditures table on LTRXPRD1 for that invoice key:
```
select OL_CAT_KEY from expenditures
where TA_INV_KEY = '309619'
order by row_date desc;
```
3. Query Symphony to see if they have 260s. They all have 264 so instead, let's edit the MARC data on morison in order to test our change to updating the expenditures table. Use `trs catalogdump -oF -ka > expenditures_test.flat`
4. Edit some records so that it's a 260 instead of 264.
5. Load the records using the ckey as match. `trs catalogload -aMARC -ba -e expenditures_test.err -hn -if -mu -um < expenditures_test.flat`
6. Confirm the records got updated:
```
echo '12216577
8053005
12216579
12216580
12216581
12216582
12216583
12216584
12216585
12216586
12216587
12216588
12216589
12216590
12216591
12216592
12216593
12216594
12216595
12216596
12216597
12216598
12216599
12216578' | trs catalogdump -oF |grep "^\.26[04]\." -P
.260.   |aMilano :|bOfficina libraria,|c[2017]
.260.   |aLucca :|bMaria Pacini Fazzi editore,|c[2017]
.264.  1|aLivorno :|bSillabe,|c[2017]
.260.   |aRome, Italy :|bDrago,|c2017.
.264.  1|aPadova :|bIl poligrafo,|c[2017]
.260.   |aGenova :|bSagep editori,|c[2017]
.260.   |aMilano, Italia :|bOfficina libraria,|c[2017]
.264.  1|aCinisello Balsamo, Milano :|bSilvana editoriale  ;|aTorino :|bAlbertina press,|c[2017]
.264.  1|aRoma :|bGangemi editore SpA international,|c[2017]
.264.  1|aRoma :|bW. Apolloni, Galleria del Laocoonte  ;|aFirenze :|bEdizioni Polistampa,|c[2017]
.260.   |aSiracusa, Italia :|bLetteraVentidue,|cmarzo 2017.
.264.  1|aTerme Vigliatore (ME) :|bGiambra editori,|cluglio 2017.
.260.   |aMilano :|bSkira,|c[2017]
.264.  1|aRoma (Italia) :|bEdizioni Quasar,|c[2017]
.260.   |aFerrara :|bEdizioni Edisai,|c[2017]
.264.  1|a[Scandolara] :|bEdizioni Stìlus,|cdicembre 2016.
.264.  1|aFirenze :|bCentro Di,|c[2017]
.264.  1|aLucca :|bEdizioni Fondazione Ragghianti studi sull'arte,|c[2017]
.264.  1|aCinisello Balsamo, Milano :|bSilvana editoriale,|c[2017]
.264.  1|aCesena :|bSocietà editrice "Il Ponte vecchio,",|c[2017]
.264.  1|aRoma :|bDe Luca editori d'arte,|c[2017]
.264.  1|aGenova :|bSagep editori,|c[2017]
.264.  1|aMilano :|bSkira,|c[2017
```
7. Update LTRXDEV2 DELPHI_PAYMENTS table for the ckeys on this invoice to look like it's been paid:
```
update DELPHI_PAYMENTS
set DELPHI_DATE = '02-MAR-18 00:22:39', SESSION_NOTE = null, RUN_TYPE = 'DEFAULT', NOTE = null, STATUS = 'PAID'
where INVOICE_ID = '309619';
```
8. Schedule run of expend_rpt.weekly_processing to populate the EXPENDITURES table.
9. Double-check that the table got updated:
```
select OL_CAT_KEY, CA_PUB260 from expenditures
where TA_INV_KEY = '309619'
and TI_INV_LINE_NUM <> 'SHIP'
and OL_CAT_KEY in (12216577,8053005,12216579,12216580,12216581,12216582,12216583,12216584,12216585,12216586,12216587,12216588,12216589,12216590,12216591,12216592,12216593,12216594,12216595,12216596,12216597,12216598,12216599,12216578)
order by row_date desc;
```

**Comment by shelleydoljack** [comment]
Submit an expenditures report for all SUL funds for pay date to AP for 02-MAR-18 to 14-FEB-20 on libsys-webforms-dev and check the Imprint column in the report..

**Comment by shelleydoljack** [comment]
Copied expend_rpt to LTRXPRD1.
