### ISSUE TITLE
Issue trying to list log files using e-loader AFS list.

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/libsys-webforms#613]
The do_afs_list package queries the vnd_runlog table to display information. Got an error.
<img width="1181" alt="Screen Shot 2019-09-10 at 11 38 09 AM" src="https://user-images.githubusercontent.com/6343464/64641069-3b162780-d3c0-11e9-9825-1f495d8793cc.png">

**Comment by jgreben** [comment]
@shelleydoljack I got it working by changing this method in `app/controllers/packages_controller.rb`:

```
 def list_transfer_logs
    @logs = VndRunlog.all.where('run_date > ?', Time.now.getlocal.strftime('%Y-%m-%d'))
  end
```

before it was:
```
@logs = VndRunlog.all.where('run_date > ?', Time.now.getlocal - 1)
```
which translated to all entries in the last second(?)

In any case, the new query will return everything from today.

Fixed by https://github.com/sul-dlss/libsys-webforms/pull/610/commits/d304fc494da041c3c3f74d945f73a77e0232b1a3 (?)

**Comment by shelleydoljack** [comment]
The Do AFS List now returns all entries for the day. The desire is that we only get a list of vnd_runlog entries for the process (and related eloader processes) that was just kicked off, which is why the query was getting all entries later than to the second minus 1. Is there a better way to query so that we get "recently run eloader packages procedures"?

**Comment by shelleydoljack** [comment]
Fixed by https://github.com/sul-dlss/libsys-webforms/pull/610/commits/7482f4587308aad7459afff232e083e25fa18b72 in #610
