### ISSUE TITLE
Handle SSDS dataset request form in libsys-webforms

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/libsys-webforms#641]
Currently there is Oracle PL/SQL code that generates a webform to submit a request to use an SSDS dataset. Links to that form are in SearchWorks, which sends variables along about the record.

We need to get the webform out of PL/SQL and have it served through Libsys-webforms code.

It does NOT need to be on the libsys-webforms menu. Just available to anyone who can webauth that clicks on the request link in SW.

**Comment by dlrueda** [comment]
example of URL being called now, so you can see what variables are included:
http://sulohsprod1.stanford.edu/swprd_ronbo/socrates_link.ssds_request_form?authid=&call_no_in=TAPE+NO.+AS1999+ETC&icpsr_no_in=&title_in=Direction+of+trade+%5Belectronic+resource%5D+%3A+original+IMF+file&unicorn_id_in=510163

so, incoming vars are:
title
ckey
call number
icpsr number

All of those values should be pre-populated in the form displayed to the user

**Comment by dlrueda** [comment]
There are other fields in the form as well, generated by PL/SQL code.  I'm checking with Ron to see if all of them are still necessary.

**Comment by dlrueda** [comment]
When user completes the form and submits, send email to 
consult-data@lists.stanford.edu

and include all fields/data from form

**Comment by dlrueda** [comment]
Current request form
![image](https://user-images.githubusercontent.com/14914677/67114377-a0fc8880-f190-11e9-99ae-8dd808f08e61.png)

**Comment by jgreben** [comment]
This will need to change as well. The URL will be different.

https://github.com/sul-dlss/shared_configs/blob/searchworks-prod/config/settings/production.yml

**Comment by jgreben** [comment]
> so, incoming vars are:
> title
> ckey
> call number
> icpsr number

In Searchworks, it looks like ot always sends the ` icpsr number` as an empty string, and only populates the `call number`:

```
def ssrc_params(document, callnumber)
    {
      authid: '',
      unicorn_id_in: document[:id],
      title_in: show_presenter(document).heading,
      icpsr_no_in: '',
      call_no_in: callnumber.callnumber
    }
  end
```

**Comment by jgreben** [comment]
What happens after they submit the form? Do they get redirected back to Searchworks, or back to the same request form with a flash notice?

**Comment by dlrueda** [comment]
Info Ron says he needs in the email he will get:

Email & Stanford affiliation is fine, plus whatever is being requested. 
Name, too, so I can personalize the response.

**Comment by dlrueda** [comment]
Josh and I talked.  They'll get a confirmation page, and there will be a link back to the SearchWorks record.

**Comment by jgreben** [comment]
Fixed by #642

**Comment by dlrueda** [comment]
Looks good!

One thought: Not sure if email of user needs to be in the email sent to SSRC upon form submission.  Ron said in the past this has just been the SUNetID@stanford.edu form of the user's email.  So maybe, since SUNetID is already included, that's good enough, they can build the email from it.  I will mention to Scott when I follow up with him.

Also, can the "Contact SSRC" for more info on the form itself (before submission) be a link to the consult-data@lists.stanford.edu email, same as it is on the confirmation page of the form after submit?

**Comment by jvine** [comment]
I have concerns about this form in its current state. Any user-facing component should have UX input to be sure it meets current usability, accessibility, and SL branding standards - the goal should be equivalent functionality rather than replicating an outdated form. In addition to the poor usability of the original, the new form does not support mobile/small devices; the footer is broken; the logo is out of date; etc.

Without completely redesigning the content of the form (which can probably wait for Requests work?) I started to make a list of changes to bring the form into alignment with our current standards. At a certain point it seemed easier to just go ahead and make some changes, so I have created a fork (https://github.com/sul-dlss/libsys-webforms/compare/ssds-dataset-form...jvine:patch-1) that includes everything that is checked in the list below. Take it as you will. :-)

## Usability

- [x] Remove the “Login here” link
   - It's not clear what the link's purpose is. It wasn't present on the original form. You can't get to the new form without logging in. It’s not necessary on a transactional form. Behaviour doesn’t follow the standard login/logout pattern. 
- [x] Make critical fields non-editable
   - User edits in these fields - intentional or accidental - will make the request more difficult to complete: SUNet ID, Dataset number, Catalog key
- [x] Use one Bootstrap row per label/input pair
   - Keep labels/inputs together for all breakpoints
   - Single-column forms have much better usability than 2-column forms
   - [x] Adjust spacing to maintain readable labels and reasonable input size at all breakpoints
   - [ ] Reorder fields once they're in a single column
- [x] Add `<meta name="viewport" content="width=device-width,initial-scale=1.0">` to `<head>` to support mobile
- [x] Change the intro text
   - Current text has negative usability. Better: use the text from the confirmation page, which gives the user an idea of what to expect.
- [x] Improve readability:
   - [x] Use sentence case for headings and field labels
   - [x] Remove colons from labels
   - [x] Include styling for `.form-control-label` style to align labels correctly (CSS below)
   - [x] Remove `<em>` from the dataset title
- [x] Add a Cancel link next to the Send button
   - This will be perceived as a transactional form, and should have a Cancel link that discards the user input and returns to the page they came from

## Accessibility

- [x] Use appropriate heading levels
   - Current `<h2>` should be `<h1>`
   - Current `<h3>` should be `<h2>`
- [x] Make the page title (currently “LibsysWebforms”) match the `<h1>`
- [x] Correct or **remove** the footer
   - There's an error in the aria-role: `<footer role="“contentinfo”" class="">` (too many quotes around `contentinfo`)
   - The footer isn't displaying in most cases - something's not right with the SU content wrapper.
   - It's unnecessary overhead for a transactional form, and creates a burden for the screen reader user.

## Branding
- [x] Replace the logo
   - Stanford University Libraries has been out of use since early 2017. Correct logo here: https://consul.stanford.edu/display/Logos/Home
   - Use the same (#1 preferred logo) for both xs and larger display. 
- [x] Remove all `<br>` elements; they interfere with spacing in unpredictable ways
- [x] Style the headings to match other properties

### CSS changes
**Update**
```
h1 {
    color: #2e2d29;
    font-size: 2.323em;
    font-weight: 300;
    line-height: 1.2em;
}
h2 {
    color: #544948;
    font-size: 1.793em;
    font-weight: 400;
    line-height: 1.2em;
}
```
**Add**
```
label.form-control-label {
    padding-top: calc(.375rem + 1px);
    padding-bottom: calc(.375rem + 1px);
    margin-bottom: 0;
    font-size: inherit;
    line-height: 1.5;
   font-weight: normal;
}
label.col-sm-4.form-control-label {
    text-align: right;
}
form#new_ssds_request {
    margin-top: 2em;
}
h2 span {
    font-weight: 300;
}
```
**and change**
```
#topnav-container #topnav
    padding: 2px 0;
to 
   padding: 5px 0;
```

## Outcome

<img width="770" alt="Screen Shot 2019-11-14 at 5 13 45 PM" src="https://user-images.githubusercontent.com/6945691/68909165-4d834900-0702-11ea-9039-0b0f5562cc97.png">

**Comment by jgreben** [comment]
@jvine I made all of the changes except  `Reorder fields once they're in a single column` because I am not exactly sure what that entails. See (e.g.) https://libsys-webforms-dev.stanford.edu/ssds_requests/new?authid=&call_no_in=TAPE+NO.+AS1999+ETC&icpsr_no_in=&title_in=Direction+of+trade+%5Belectronic+resource%5D+%3A+original+IMF+file&unicorn_id_in=510163

**Comment by jvine** [comment]
The fields are in the correct order after your changes, so nothing further needed there. 

However, some other corrections are needed to get the layout working as it should. 

- [x] **line 18**: ` <div>` should be `  <div class='col-sm-9 col-md-7 col-lg-6'>`. This parent div controls the form width for all breakpoints.
- [x] **line 20** and all following instances: `col-sm col-md-4` should be `col-sm-4`. `col-sm` without a number does nothing; and we don't need separate `-sm` and `-md` settings on individual fields, because the parent div manages it all. 
- [x] **line 21** and all following instances: `col-sm col-md-4` should be `col-sm-8`. Again, this works with the parent div.
- [x] **line 55**: where you have ` <hr />` followed by `<h2>` - the example I gave closes the `<div>` opened on line 18, creates a new `<div>` for the `<h2>`, then opens a third `<div>` for the rest of the form. This gives each section the best width for its content. At a minimum, please remove the `<hr>`.
    ```
  ...form so far...
   </div>  
   <div class="col-sm-12">
      <h2 class="row">...</h2>		
  </div>		
  <div class='col-sm-9 col-md-7 col-lg-6'>
  ...remainder of form...
   ```
- [x] **line 75**: (text area div) - `<div class='field'>` should be `<div class='form-group row'>`
- [x] **line 77**: `<div>` should be `<div class='col-sm-8'>`
- [x] **line 78**: `class: 'fill-width'` should be `class: 'form-control'`. These three changes together allow the flexbox to control the size of the text field more gracefully at all breakpoints. 

Let me know if you have any questions.

**Comment by jgreben** [comment]
@jvine I made the changes you specified, but the form does not look right to me. The notes field is not right and the rest of the fields no longer collapse on a smaller display. I deployed it to dev so you can take a look at the same link above ☝️

**Comment by shelleydoljack** [comment]
The fields collapse for me in chrome and safari. The only field that looks out of place is the notes field.

**Comment by jvine** [comment]
Notes field: My mistake, pls change line 80 `<div class='col-sm-8'>` to `<div class='col-sm-12'>`

The fields do collapse to two rows on mobile (at size -xs, see screenshot). They are not intended to collapse for -sm, because it can result in fields over 750px wide before it switches to -md, and that's not desirable. It's a tradeoff between awkward sizing at some in-between widths, and appropriate sizing for specific devices. 

On testing mobile, I noticed that the logo disappears. When you deleted the second image (intended for display on mobile), you left the `class="hidden-xs"` in the first, which suppresses its display on mobile. 

And the `<h1>` heading was not changed: "Use sentence case for headings and field labels". Please change `SSRC Dataset Request Form` to `SSRC dataset request` in the `<h1>` and `<title>`.

<img width="378" alt="Screen Shot 2019-11-19 at 9 44 11 AM" src="https://user-images.githubusercontent.com/6945691/69173708-2a1b1e00-0ab5-11ea-8846-96ba9245a6df.png">

**Comment by jgreben** [comment]
Ok @jvine I deployed those changes.

**Comment by jvine** [comment]
@jgreben I see you've also added an `alt=` value to the image. The empty `alt=""` was intentional (in all our applications) because the link text is provided in the `<span>` that precedes the image. Now the link text reads to a screen-reader as "Stanford University Libraries Stanford Libraries". 

![linktext](https://user-images.githubusercontent.com/6945691/69180207-be8b7d80-0ac1-11ea-9987-a5745e56dc3e.gif)

I mean... the text wasn't correct to start with ("University"), but now it's worse.

**Comment by jgreben** [comment]
ok @jvine I changed it back.

**Comment by dlrueda** [comment]
Doing a final test...

Submitting form works fine, I see the email is sent to sul-unicorn-devs.

When I click the cancel button it re-displays the form right now.  I believe it's supposed to return me to the SearchWorks record?

**Comment by jvine** [comment]
Yes, it should go to the SW record or page you came from. (I believe it's possible to get to this form directly from search results).

**Comment by jgreben** [comment]
Fixed.

**Comment by jvine** [comment]
Two more things:

1. Darsi has found a record with multiple call numbers associated with a single request button. 
https://searchworks-morison.stanford.edu/view/13028075
Because we are only passing one call number into the form, we are going to have to allow that field to be editable after all, so the user can change it to reflect the specific call number they want. It's not a good solution, but best available under the circumstances.

- [x] Remove readonly from the call number input.

2. The Cancel link. By "it should go to the SW record or page you came from" I meant the _SearchWorks_ page that you came from, which might be a record or a search result. It should not just go to the "last page in your history", because in some cases that will be the login page, which will give an error. 

- [x] If it's not possible to retain the "SearchWorks page where the Request button was clicked", then just use the same link as on the confirmation page.

**Comment by dlrueda** [comment]
Working!!! Ship it!!
